server {
    listen 80;
    server_name tsa233.lab www.tsa233.lab;

    root /usr/share/nginx/html;
    index index.html;

    # Логування
    access_log /var/log/nginx/tsa233.access.log;
    error_log  /var/log/nginx/tsa233.error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
